spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: master,slave1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: root
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: root
    sharding:
      #读写分离
      master-slave-rules:
        master:
          name: # 读写分离数据源名称
          master-data-source-name: master # 主库数据源名称
          slave-data-source-names: # 从库数据源名称列表
            - slave1
          loadBalanceAlgorithmType: ROUND_ROBIN # 从库负载均衡算法类型，可选值：ROUND_ROBIN，RANDOM。若`loadBalanceAlgorithmClassName`存在则忽略该配置
          props:  # 读写分离负载算法的属性配置
      # 分表规则
      tables:
        #scs_product可以任意命名，sql中一致，为了方便理解，这里一般写分表共有的
        # 比如我的scs_product_1  和 scs_product_2  那就写scs_product好区分
        # 当执行sql中出现scs_product，sharding-jdbc会将其操作到对应的表
        scs_product:
          actual-data-nodes: db1.scs_product_$->{1..2}
          # 指定主键生成策略为雪花id,全局主键
          key-generator:
            column: PRODUCT_ID
            type: SNOWFLAKE
          #指定scs_product表的分片策略，  分片键和分片算法 用于计算真正的表名
          table-strategy:
            inline:
              # 偶数进到scs_product_1  奇数进到scs_product_2
              # 对于根据分片字段为条件的，会先判断是否涉及两张表，
              # 如何是两张表则会两个表都查，如果只涉及单表，则只查询一张表。
              algorithm-expression: scs_product_$->{PRODUCT_ID % 2 + 1}
              # 指定分片键为PRODUCT_ID
              sharding-column: PRODUCT_ID

    props: # 属性配置
      sql:
        show: true #是否开启SQL显示，默认值: false
      # executor.size: #工作线程数量，默认值: CPU核数
      # max.connections.size.per.query: # 每个查询可以打开的最大连接数量,默认为1
      # check.table.metadata.enabled: #是否在启动时检查分表元数据一致性，默认值: false